Quick commit - 2026/01/18 10:00

diff --git a/scripts/templates/deploy-remote b/scripts/templates/deploy-remote
--- a/scripts/templates/deploy-remote
+++ b/scripts/templates/deploy-remote
@@ -10,23 +10,24 @@ script_name=PROJECT
 remote_dir="/var/www/${script_name}"
 
 echo -e "${GREEN}[${script_name}] Running git pull...${NC}"
-ssh "$server" "git -C ${remote_dir} config core.sshCommand 'ssh -i /home/ifor/.ssh/id_rsa' && git -C ${remote_dir} pull"
+ssh "$server" "git -C ${remote_dir} pull"
 
 echo -e "${GREEN}[${script_name}] Building assets...${NC}"
+if ! command -v npm &>/dev/null; then
+  echo -e "${RED}[${script_name}] npm not found!${NC}"
+  exit 1
+fi
 npm run build
 
-echo -e "${GREEN}[${script_name}] Copying CSS files to remote...${NC}"
-rsync -avz --progress "assets/output.css" "${server}:${remote_dir}/assets/output.css"
-
-# echo -e "${GREEN}[${script_name}] Copying build files to remote...${NC}"
-# rsync \
-#   --verbose \
-#   --compress \
-#   --recursive \
-#   --omit-dir-times \
-#   --times \
-#   public/build/* \
-#   "${server}:${remote_dir}/public/build"
+echo -e "${GREEN}[${script_name}] Copying build files to remote...${NC}"
+rsync \
+  --verbose \
+  --compress \
+  --recursive \
+  --omit-dir-times \
+  --times \
+  public/build/ \
+  "${server}:${remote_dir}/public/build/"
 # rsync \
 #   --verbose \
 #   --compress \
@@ -37,8 +38,8 @@ rsync -avz --progress "assets/output.css" "${server}:${remote_dir}/assets/output
 #   storage/app/public/* \
 #   "${server}:${remote_dir}/storage/app/public"
 
-# echo -e "${GREEN}[${script_name}] Running deploy script on remote...${NC}"
-# ssh "$server" "${remote_dir}/deploy-local"
+echo -e "${GREEN}[${script_name}] Running deploy script on remote...${NC}"
+ssh "$server" "${remote_dir}/deploy-local"
 
 echo -e "${GREEN}[${script_name}] All done!${NC}"
 exit 0
