Update mysql script.

diff --git a/scripts/server/4_install_mysql b/scripts/server/4_install_mysql
--- a/scripts/server/4_install_mysql
+++ b/scripts/server/4_install_mysql
@@ -6,17 +6,50 @@ if [[ $(/usr/bin/id -u) -ne 0 ]]; then
     exit 1
 fi
 
+root_pass=${1-:}
+new_user_name=${2-:}
+new_user_pass=${3-:}
+new_databases="${@:4}"
+
+if [[ -z root_pass ]]; then
+    echo -n "[${name}] Enter mysql root password: "
+    read -rs root_pass
+    echo
+    read -rs -p "[${name}] Confirm password: " ROOT_PASS_CONFIRM
+    if [ "${root_pass}" != "${ROOT_PASS_CONFIRM}" ]; then
+        echo "[${name}] Passwords do not match."
+        exit 1
+    fi
+done
+
+if [[ -z new_user_name ]]; then
+    read -r -p "[${name}] Enter a new server username: " new_user_name
+    if [[ -z $new_user_name ]]; then
+        echo "[${name}] Username cannot be empty."
+        exit 1
+    fi
+done
+
+if [[ -z new_user_pass ]]; then
+    echo -n "[${name}] Enter mysql new user password: "
+    read -rs new_user_pass
+    echo
+    read -rs -p "[${name}] Confirm password: " NEW_USER_PASS_CONFIRM
+    if [ "${new_user_pass}" != "${NEW_USER_PASS_CONFIRM}" ]; then
+        echo "[${name}] Passwords do not match."
+        exit 1
+    fi
+done
+
+if [[ -z new_databases ]]; then
+    read -r -p "[${name}] If you wish to create new databases, enter a space delimited list of their names: " new_databases
+done
+
 if [[ "$#" -lt 3 ]]; then
     echo "[${name}] Please enter a mysql root password, mysql new user name and new user password."
     echo "[${name}] Usage: ./install_mysql ROOT_PASS NEW_USER_NAME NEW_USER_PASS"
     exit 1
 fi
-
-
-root_pass=$1
-new_user_name=$2
-new_user_pass=$3
-new_databases="${@:4}"
 
 echo $new_databases; exit
 echo "[${name}] Installing."
