WIP

diff --git a/scripts/server/optimise_nginx b/scripts/server/optimise_nginx
--- a/scripts/server/optimise_nginx
+++ b/scripts/server/optimise_nginx
@@ -11,9 +11,16 @@ fi
 
 echo "[${name}] Backing up current nginx config."
 mv "${base_dir}" "${base_dir}.bak"
+if [[ $? -ne 0 ]]; then
+    echo "[${name}] Failed to move current nginx config. Exiting."
+fi
 
 echo "[${name}] Cloning h5bp nginx config."
 git clone --depth 1 git@github.com:h5bp/server-configs-nginx.git "${base_dir}"
+if [[ $? -ne 0 ]]; then
+    echo "[${name}] Failed to clone h5bp nginx config. Using local copy."
+    tar xzvf "$(dirname $(realpath -s $0))/h5bp-server-configs.tar.gz" --directory="${base_dir}.bak/.."
+fi
 
 echo "[${name}] Force redirect all non-https requests to https."
 sed -i "s|# return 301 https://\$host\$request_uri;|return 301 https://\$host\$request_uri;|" "${base_dir}/conf.d/no-ssl.default.conf"
@@ -29,7 +36,17 @@ for f in "$base_dir".bak/sites-enabled/*; do mv "${base_dir}/conf.d/.${f##*/}.co
 echo "[${name}] Adding h5bp basic configuration include to existing site configs."
 shopt -s dotglob
 for f in "$base_dir"/conf.d/*; do sed -i '/fpm.sock/,/}/ s/}/} \n\n    include h5bp\/basic.conf;\n\n/' "$f"; done
+for f in "$base_dir"/conf.d/.*; do sed -i '/fpm.sock/,/}/ s/}/} \n\n    include h5bp\/basic.conf;\n\n/' "$f"; done
 shopt -u dotglob
+
+
+echo "[${name}] Optimising individual server configs."
+for f in "$base_dir"/conf.d/.*; do
+   ./optimise_nginx_domain_config "$f"
+done
+for f in "$base_dir"/conf.d/*; do
+   ./optimise_nginx_domain_config "$f"
+done
 
 config_test=$(nginx -t 2>&1|grep 'test is successful')
 if [[ -z "${config_test}" ]]; then
diff --git a/scripts/server/optimise_nginx_domain_config b/scripts/server/optimise_nginx_domain_config
--- a/scripts/server/optimise_nginx_domain_config
+++ b/scripts/server/optimise_nginx_domain_config
@@ -4,6 +4,7 @@ name=OPTIMISE_NGINX_DOMAIN_CONFIG
 usage="usage: ./optimise_nginx_domain_config CONFIG_FILE"
 
 config_file=$1
+force_www=0
 
 if [[ $(/usr/bin/id -u) -ne 0 ]]; then
     echo "[${name}] This script must be run as root (or sudo). Exiting."
@@ -16,21 +17,33 @@ if [[ "$#" -lt 1 ]]; then
     exit 1
 fi
 
+if [[ -d "$config_file" ]]; then
+    echo "[${name}] Specified path is a directory, aborting."
+    exit 1
+fi
+
 if [[ ! -e "${config_file}" ]]; then
     echo "[${name}] Config file does not exist, aborting."
     exit 1
 fi
 
-echo "[${name}] Creating backup file."
-cp "$config_file" ".${config_file}.bak"
+if [[ "$#" -eq 2 ]]; then
+    echo "forcing www"
+    exit 1
+fi
+
+echo "[${name}] Creating backup file for ${config_file}."
+output_filepath="${config_file%/*}/.${config_file##*/}.bak"
+output_filepath=${output_filepath/../.}
+cp -v "$config_file" "${output_filepath}"
 
 domain_name=$(sed -rn '/server_name/ s/server_name ([ a-z].*);/\1/p' "$config_file" | head -1 | xargs)
 
 server_block_count=$(grep -c 'server ' "$config_file")
 if [[ "$server_block_count" -gt 1 ]]; then
     echo "[${name}] Removing managed by certbot lines."
-    tac "$config_file" | sed '0,/server {/d' | tac | sed '/# managed by Certbot/d;' | sed '/^$/N;/^\n$/D' > "$config_file".bak
-    mv "${config_file}.bak" "$config_file"
+    tac "$config_file" | sed '0,/server {/d' | tac | sed '/# managed by Certbot/d;' | sed '/^$/N;/^\n$/D' > "$config_file".tmp
+    mv -v "${config_file}.tmp" "$config_file"
 fi
 
 echo "[${name}] Removing listen directive."
