WIP

diff --git a/scripts/server/optimise_php_fpm b/scripts/server/optimise_php_fpm
--- a/scripts/server/optimise_php_fpm
+++ b/scripts/server/optimise_php_fpm
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
-php_version=$(php -r 'echo PHP_VERSION;'|awk -F. '{print $1"."$2}')
+name=OPTIMISE_PHP_FPM
+php_version=$(php -r 'echo PHP_VERSION;' | awk -F. '{print $1"."$2}')
 
 fpm_config=/Users/ifor/Downloads/www.conf
 fpm_config="/etc/php/${php_version}/fpm/pool.d/www.conf"
@@ -15,17 +16,17 @@ max_spare_servers=10
 max_requests=500
 
 if [[ ! -r "${fpm_config}" ]]; then
-   echo "Unable to read config file at ${fpm_config}"
-   echo "Aborting..."
+   echo "[${name}] Unable to read config file at ${fpm_config}"
+   echo "[${name}] Aborting..."
    exit 1
 fi
 
-echo "Active config file: ${fpm_config}"
+echo "[${name}] Active config file: ${fpm_config}"
 echo
-echo "Current settings:"
+echo "[${name}] Current settings:"
 grep '^;\?pm.max_children\|^;\?pm.start_servers\|^;\?pm.min_spare_servers\|^;\?pm.max_spare_servers\|^;\?pm.max_requests' "${fpm_config}"|grep -v ";"|sed 's/pm\.//'
 echo
-echo "Proposed settings:"
+echo "[${name}] Proposed settings:"
 echo "max_children = ${max_children}"
 echo "start_servers = ${start_servers}"
 echo "min_spare_servers = ${min_spare_servers}"
@@ -33,41 +34,41 @@ echo "max_spare_servers = ${max_spare_servers}"
 echo "max_requests = ${max_requests}"
 echo
 
-# read -p "Do you want to update the FPM config file? (y/n) " -n 1 -r
-# echo
-# if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-#    echo
-#    echo "Aborting..."
-#    exit 1
-# fi
-
+read -p "[${name}] Do you want to update the FPM config file? (y/n) " -n 1 -r
 echo
-echo "Updating config file..."
-sed -E "s/^;?pm.max_children.*/pm.max_children = ${max_children}/; s/^;?pm.start_servers.*/pm.start_servers = ${start_servers}/; s/^;?pm.min_spare_servers.*/pm.min_spare_servers = ${min_spare_servers}/; s/^;?pm.max_spare_servers.*/pm.max_spare_servers = ${max_spare_servers}/; s/^;?pm.max_requests.*/pm.max_requests = ${max_requests}/;" "${fpm_config}"|sudo tee "${fpm_config}" >/dev/null
-
-config_test=$(sudo php-fpm${php_version} -t 2>&1|grep 'test is successful')
-if [[ -z "${config_test}" ]]; then
-   echo "Config test failed, please manually check (php-fpm${php_version} -t) and try again."
+if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+   echo
+   echo "[${name}] Aborting..."
    exit 1
 fi
 
 echo
-echo "Optimised settings:"
+echo "[${name}] Updating config file..."
+sed -E "s/^;?pm.max_children.*/pm.max_children = ${max_children}/; s/^;?pm.start_servers.*/pm.start_servers = ${start_servers}/; s/^;?pm.min_spare_servers.*/pm.min_spare_servers = ${min_spare_servers}/; s/^;?pm.max_spare_servers.*/pm.max_spare_servers = ${max_spare_servers}/; s/^;?pm.max_requests.*/pm.max_requests = ${max_requests}/;" "${fpm_config}"|sudo tee "${fpm_config}" >/dev/null
+
+config_test=$(sudo php-fpm${php_version} -t 2>&1|grep 'test is successful')
+if [[ -z "${config_test}" ]]; then
+   echo "[${name}] Config test failed, please manually check (php-fpm${php_version} -t) and try again."
+   exit 1
+fi
+
+echo
+echo "[${name}] Optimised settings:"
 grep '^;\?pm.max_children\|^;\?pm.start_servers\|^;\?pm.min_spare_servers\|^;\?pm.max_spare_servers\|^;\?pm.max_requests' "${fpm_config}"|grep -v ";"|sed 's/pm\.//'
 
 echo
-# read -p "Settings updated, you need to restart the FPM service for these changes to take effect, restart now? (y/n) " -n 1 -r
-# echo
-# if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-#    echo
-#    echo "Service not restarted."
-#    exit 1
-# else
+read -p "[${name}] Settings updated, you need to restart the FPM service for these changes to take effect, restart now? (y/n) " -n 1 -r
+echo
+if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo
-   echo "Restarting FPM service"
+   echo "[${name}] Service not restarted."
+   exit 1
+else
+   echo
+   echo "[${name}] Restarting FPM service"
    sudo service php${php_version}-fpm restart
    echo
-   echo "Service restarted."
+   echo "[${name}] All done!"
    exit 0
-# fi
+fi
 
