Rename scripts to use underscores

diff --git a/scripts/_example b/scripts/_example
--- a/scripts/_example
+++ b/scripts/_example
@@ -1,4 +1,6 @@
 #!/bin/bash
+#
+# Example bash script
 
 set -o errexit  # Exit the script if any command fails (add "|| true" to allow failing)
 set -o nounset  # Exit the script if an undeclared variable is used
@@ -8,6 +10,10 @@ set -o pipefail # Exit the script if an error occurs in a pipe
 
 # TODO
 # Warnings and errors should go to STDERR, anything parsable should go to STDOUT.
+
+err() {
+      echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
+  }
 
 _log()
 {
@@ -53,6 +59,9 @@ _main()
     else
         echo "Unknown."
     fi
+
+    err "Some error message"
+
     echo sleeping
     sleep 3
     exit 0
