Update deploy script

diff --git a/scripts/deploy_remote b/scripts/deploy_remote
--- a/scripts/deploy_remote
+++ b/scripts/deploy_remote
@@ -1,31 +1,35 @@
 #!/bin/bash
-# set -x
+
+if [[ -n $DEBUG ]]; then
+    set -x
+fi
+
+if [[ $# -lt 2 ]]; then
+    echo "Local and remote addresses required. Aborting..."
+    exit 1
+fi
 
 local="$1"
 remote="$2"
-owner="${3:-www-data}"
-group="${4:-www-data}"
-perms="${5:-D2775,F664}"
-include=()
-exclude=(
-    .env
-    .git
-    .gitignore
-    .DS_Store
-    deploy_remote
-    tags
-    vendor
-    node_modules
-)
+include="$3"
+exclude="${4:-.env;.git;.gitignore;.DS_Store;deploy_remote;tags;vendor;node_modules}"
+owner="${5:-www-data}"
+group="${6:-www-data}"
+# perms="${7:-D2775,F664}"
 
 include_opts=()
-for item in "${include[@]}"; do
+IFS=';' read -ra arg <<< "$include"
+for item in "${arg[@]}"; do
     include_opts+=( --include="$item" )
 done
+
 exclude_opts=()
-for item in "${exclude[@]}"; do
+IFS=';' read -ra arg <<< "$exclude"
+for item in "${arg[@]}"; do
     exclude_opts+=( --exclude="$item" )
 done
+
+# --chmod="${perms}" \
 
 rsync \
     ${DRYRUNARG:+"$DRYRUNARG"} \
@@ -34,13 +38,11 @@ rsync \
     --compress \
     --times \
     --omit-dir-times \
-    --perms \
     --fake-super \
     --owner \
     --group \
     --usermap="\*:${owner}" \
     --groupmap="\*:${group}" \
-    --chmod="${perms}" \
     "${include_opts[@]}" \
     "${exclude_opts[@]}" \
     --delete \
