Update repo (2023/02/22 14:04).

diff --git a/scripts/logic_stem_export b/scripts/logic_stem_export
--- a/scripts/logic_stem_export
+++ b/scripts/logic_stem_export
@@ -26,18 +26,20 @@ function count_unique() {
 # 3. Set all stem outputs to a common bus
 # 4. Add the common bus to the track list (Ctrl + T)
 # 5. File > Export > All Tracks as Audio Files... (Shift + Cmd + E)
-# 6. Set the "Range" to Extend File Length to Project Length
-# 7. Rename common bus to mix.wav
-# 8. List Editors (D) > Markers
-# 9. View > Check both "Show Event Time Position and
+# 6. Enable "Include Volume/Pan Automation"
+# 7. Set the "Range" to Extend File Length to Project Length
+# 8. Rename common bus output file to mix.wav
+# 9. List Editors (D) > Markers
+# 10. View > Check both "Show Event Time Position and
 #    Length as Time" and "Length as Absolute Position"
-# 10. Copy all marker info and paste into a file called markers
+# 11. Copy all marker info and paste into a file called markers
 
 # Marker file example:
 # 00:00:00:00.00  chill    00:02:31:19.57
 # 00:02:38:06.42  drum_groove  00:00:16:17.33
 
 directory_path="${1-}"
+skip_mp3="${2-}"
 
 if [[ -z "$directory_path" ]]; then
     echo "[ERROR] A path to the WAV files is required, exiting..."
@@ -46,6 +48,16 @@ fi
 
 if [[ ! -d "$directory_path" ]]; then
     echo "[ERROR] Path provided is not a directory, exiting..."
+    exit 1
+fi
+
+if ! [ -x "$(command -v ffmpeg)" ]; then
+    echo "[ERROR] ffmpeg is not installed, exiting..."
+    exit 1
+fi
+
+if ! [ -x "$(command -v ffprobe )" ]; then
+    echo "[ERROR] ffprobe is not installed, exiting..."
     exit 1
 fi
 
@@ -96,7 +108,11 @@ for f in "${directory_path}"/*.wav; do
         marker_name=$(echo "$line" | awk '{print $2}')
         start_time=$(echo "$line" | awk '{print $1}' | sed 's/\([0-9]\{1,2\}:[0-9]\{2\}:[0-9]\{2\}\):\([0-9]\{2\}\).\([0-9]\{2\}\)/\1.\2\3/')
         duration=$(echo "$line" | awk '{print $3}' | sed 's/\([0-9]\{1,2\}:[0-9]\{2\}:[0-9]\{2\}\):\([0-9]\{2\}\).\([0-9]\{2\}\)/\1.\2\3/')
-        new_filename="${f%/*}/output/${f##*/}"
+
+        new_directory_path="${f%/*}output/${marker_name}"
+        mkdir -p "$new_directory_path"
+
+        new_filename="${new_directory_path}/${f##*/}"
         new_filename="${new_filename%.wav}_${marker_name}.wav"
 
         echo
@@ -114,17 +130,21 @@ done
 
 # TODO: Make MP3 conversion optional?
 
-echo "[INFO] Converting WAV files to MP3..."
-for f in "${directory_path}/output"/*.wav; do
-    ffmpeg \
-        -y \
-        -i "$f" \
-        -write_id3v1 1 \
-        -id3v2_version 3 \
-        -dither_method triangular \
-        -b:a 192k \
-        "${f%.wav}.mp3"
-done
+if [[ -n "$skip_mp3" ]]; then
+    echo "Skipping MP3 generation..."
+else
+    echo "[INFO] Converting WAV files to MP3..."
+    for f in "${directory_path}/output"/**/*.wav; do
+        ffmpeg \
+            -y \
+            -i "$f" \
+            -write_id3v1 1 \
+            -id3v2_version 3 \
+            -dither_method triangular \
+            -b:a 192k \
+            "${f%.wav}.mp3"
+        done
+fi
 
 # TODO: Create tracks missing an instrument
 # ffmpeg -i INPUT_1 -i INPUT_2 -filter_complex amix=inputs=NUMBER_OF_INPUTS:duration=first OUTPUT
