Update repo (2023/12/31 12:14).

diff --git a/scripts/mscreate b/scripts/mscreate
--- a/scripts/mscreate
+++ b/scripts/mscreate
@@ -4,11 +4,13 @@ blue='\033[0;34m'
 green='\033[0;32m'
 red='\033[0;31m'
 nc='\033[0m'
+
 name="MuseScore"
 base_dir="/Users/ifor/Documents/MuseScore4"
 style_file_path="${base_dir}/Styles/my_style.mss"
-output_dir="/Users/ifor/Downloads"
 output_dir="${base_dir}/Scores"
+date_now=$(date "+%Y-%m-%d")
+time_signature_subtype=0
 
 script_path=$(dirname "$(realpath -s "$0")")
 audio_file_path="${script_path}/musescore_audio.json"
@@ -19,42 +21,66 @@ declare -rA key_signatures=(
 )
 
 song_title="$1"
-date_now=$(date "+%Y-%m-%d")
+if [[ $# -gt 1 ]]; then
+  echo "Entering auto-mode!"
 
-if [[ -z "$song_title" ]]; then
-  read -p "[${name}] Enter the song title: " -r song_title
+  composer="$2"
+  artist_name="$3"
+  album_name="$4"
+  tempo="$5"
+  key_signature="$6"
+  time_signature_raw="$7"
+  part_musician="$8"
+  no_of_bars="$9"
+else
   if [[ -z "$song_title" ]]; then
-     echo
-     echo -e "${red}[${name}] Song title required, aborting.${nc}"
-     exit 1
+    read -p "[${name}] Enter the song title: " -r song_title
+    if [[ -z "$song_title" ]]; then
+       echo
+       echo -e "${red}[${name}] Song title required, aborting.${nc}"
+       exit 1
+    fi
   fi
+
+  read -p "[${name}] Enter the composer (optional): " -r composer
+  read -p "[${name}] Enter the artist name (optional): " -r artist_name
+  read -p "[${name}] Enter the album name and year (optional): " -r album_name
+  read -p "[${name}] Enter song tempo (optional): " -r tempo
+  read -p "[${name}] Enter the major key signature (optional): " -r key_signature
+  read -p "[${name}] Enter the time signature (X/Y, c: common, c-: cut) (optional): " -r time_signature_raw
+  read -p "[${name}] For a solo piece, enter the musician playing this part (Instrument: Musician - optional): " -r part_musician
+  read -p "[${name}] Enter number of bars (optional): " -r no_of_bars
 fi
 
-filename="${song_title,,}"
-filename="${filename// /.}"
-
+filename=$(echo $song_title | sed "
+  s/[^[:alnum:]_\/\ \.-]//g;
+  s/ /./g;
+")
+filename="${filename,,}"
 if [[ -e "${output_dir}/${filename}.mscz" ]]; then
    echo -e "${red}[${name}] A file with that name already exists, aborting.${nc}"
    exit 1
 fi
 
-read -p "[${name}] Enter the artist name (optional): " -r artist_name
-read -p "[${name}] Enter the album name and year (optional): " -r album_name
-read -p "[${name}] Enter song tempo (optional): " -r tempo
 tempo="${tempo:-120}"
-read -p "[${name}] Enter the key signature (optional): " -r key_signature
-key_signature="${key_signature:-C}"
-read -p "[${name}] Enter the time signature (optional): " -r time_signature
-time_signature="${time_signature:-4/4}"
-read -p "[${name}] Enter the composer (optional): " -r composer
-read -p "[${name}] Enter the musician playing this part (optional): " -r part_musician
-read -p "[${name}] Enter number of bars (optional): " -r no_of_bars
-no_of_bars="${no_of_bars:-32}"
-
-time_signature_top=$(echo $time_signature | awk -F'/' '{print $1}')
-time_signature_btm=$(echo $time_signature | awk -F'/' '{print $2}')
 tempo_decimal=$(echo "${tempo}/60" | bc -l | cut -c -10)
 
+no_of_bars="${no_of_bars:-32}"
+
+time_signature_raw="${time_signature_raw:-4/4}"
+time_signature="$time_signature_raw"
+if [[ $time_signature_raw == 'c' ]]; then
+  time_signature="4/4"
+  time_signature_subtype=1
+fi
+if [[ $time_signature_raw == 'c-' ]]; then
+  time_signature="2/2"
+  time_signature_subtype=2
+fi
+time_signature_top=$(echo $time_signature | awk -F'/' '{print $1}')
+time_signature_btm=$(echo $time_signature | awk -F'/' '{print $2}')
+
+key_signature="${key_signature:-C}"
 if [[ -v "key_signatures[${key_signature}]" ]] ; then
   key_signature_int="${key_signatures[$key_signature]}"
 else
@@ -62,8 +88,19 @@ else
   key_signature_int=0
 fi
 
-view_settings='{"notation":{"viewMode":"continuous_h"}}'
+echo -e "${green}Song Details:
+Composer: ${composer}
+Title: ${song_title}
+Artist: ${artist_name}
+Album: ${album_name}
+Tempo: ${tempo}
+Key Sig: ${key_signature}
+Time Sig: ${time_signature} (${time_signature_raw})
+Part Musician: ${part_musician}
+No of Bars: ${no_of_bars}
+${nc}"
 
+view_settings='{"notation":{"viewMode":"continuous_h"}}'
 meta_inf="<?xml version=\"1.0\" encoding=\"UTF-8\"?>
 <container>
   <rootfiles>
@@ -93,6 +130,11 @@ cp -v "$style_file_path" "${output_dir}/${filename}/"
 echo "Generating faux thumbnail."
 convert -size "181x256" canvas:white "${output_dir}/${filename}/Thumbnails/thumbnail.png"
 
+time_signature_subtype_replacement=""
+if [[ $time_signature_subtype -ne 0 ]]; then
+  time_signature_subtype_replacement="<subtype>${time_signature_subtype}</subtype>"
+fi
+
 echo "Generating mscx file."
 sed "
 s|XXTITLEXX|${song_title}|g;
@@ -104,6 +146,7 @@ s|XXTEMPO_DECIMALXX|${tempo_decimal}|g;
 s|XXCREATIONXX|${date_now}|g;
 s|XXEXTRAXX|${part_musician}|g;
 s|XXTIME_SIGNATUREXX|${time_signature}|g;
+s|XXTIME_SIG_SUBTYPEXX|${time_signature_subtype_replacement}|g;
 s|XXKEY_SIGNATUREXX|${key_signature_int}|g;
 s|XXTIME_SIG_TOPXX|${time_signature_top}|g;
 s|XXTIME_SIG_BTMXX|${time_signature_btm}|g;
@@ -132,8 +175,13 @@ echo "    <Staff id=\"2\">
             <linked></linked>
             <concertKey>${key_signature_int}</concertKey>
           </KeySig>
-          <TimeSig>
-            <eid>171798691864</eid>
+          <TimeSig>" >> "${output_dir}/${filename}/${filename}.mscx"
+
+if [[ $time_signature_subtype -ne 0 ]]; then
+  echo "            <subtype>${time_signature_subtype}</subtype>" >> "${output_dir}/${filename}/${filename}.mscx"
+fi
+
+echo "            <eid>171798691864</eid>
             <sigN>${time_signature_top}</sigN>
             <sigD>${time_signature_btm}</sigD>
           </TimeSig>
